#!/bin/sh

# TODO: Randomize the exposed port

name=bitemporal-sql-example

docker run \
    -d \
    --rm \
    --name $name \
    -p 5432:5432 \
    -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test \
    --mount type=tmpfs,destination=/var/lib/postgresql/data \
    -v "$PWD"/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d \
    postgres:13.2-alpine \
    -c fsync=off >/dev/null

while ! docker exec -it $name pg_isready -q -d test -U test ; do
    sleep 1
done

docker exec -it $name kill -TERM 1
